### ISSUE TITLE
Camera Clients in CTF mode see Join menu instead of Scoreboard at Intermission

### ISSUE THREAD

**Issue by QwazyWabbitWOS** [QwazyWabbitWOS/chaos#1]
Clients in any camera mode see the CTF join menu instead of the scoreboard. F1 will still present the scoreboard but it has to be done manually.

**Comment by MrG-DRGN** [comment]
if it's level.intermissiontime the join menu shouldn't be shown.

**Comment by MrG-DRGN** [comment]
I'm not sure if we can fix this other than by making some kind of was_cam variable that doesn't get reset by PutClientInServer. The client exit camera at map end.

**Comment by QwazyWabbitWOS** [comment]
I think it might be worthwhile to explore restoring the spectator command and variable that is in the 3.20/3.21 game. I don't know if this was in earlier versions but "spectator 1" is a well-known and typical command for gaining spectator access. This would give a single flag to test for whether spectator mode is on for any client.

**Comment by MrG-DRGN** [comment]
There is a lot of extra code associated with that that I don't feel is necessary (passwords for spectator, etc). It was not in earlier versions to the best of my knowledge. I know spectator and observer from the CTF codebase will clash in places.  I can start adding the appropriate code in.

**Comment by MrG-DRGN** [comment]
right now spectator and observer work to bring the player into that ctf joinmenu in ctf. the camera 1-4 work for dm

**Comment by QwazyWabbitWOS** [comment]
That's not what I had in mind so no importation of that code is needed at this time. The spectator and player password isn't needed, for one thing.

**Comment by MrG-DRGN** [comment]
Good deal. I've started replacing the multiple conditionals to check for observer and camera movetypes with one check for resp.spectator.

**Comment by QwazyWabbitWOS** [comment]
CTF mode preserves spectator/team status. DM auto-places clients into game at crossover. Camera issues seem to be resolved. Closing.
