### ISSUE TITLE
Switching from CTF to DM at Intermission causes DM Scoreboard to show

### ISSUE THREAD

**Issue by QwazyWabbitWOS** [QwazyWabbitWOS/chaos#2]
When game changes modes from CTF to DM due to map mode change the DM scoreboard shows at intermission instead of the CTF scoreboard. Map rotations can mix CTF and DM maps. Mode should change after intermission completes and starts a new map, not before.

**Comment by MrG-DRGN** [comment]
I'm pretty sure DM to CTF does the same in reverse. Is there a defined point between imtermissiontime and the next map being loaded we can change the CTF cvar in?

**Comment by MrG-DRGN** [comment]
Resolved by QW
