### ISSUE TITLE
Bot weapon search malfunctions if DF_WEAPONS_STAY is set.

### ISSUE THREAD

**Issue by QwazyWabbitWOS** [QwazyWabbitWOS/chaos#3]
Bots apparently keep trying to touch weapons when DF_WEAPONS_STAY is set. They're either not checking inventory to see they already have it or they don't un-focus on the seek after the pickup when the weapon doesn't disappear.

**Comment by MrG-DRGN** [comment]
I'm fairly certain they don't check inventory. I'll extend the code I made that checks if they have a grappling hook or keys in inventory to the weapon items, and go from there. Ultimately, they should probably ignore ammo, if they have the MAX_"AMMO" in inventory.

**Comment by MrG-DRGN** [comment]
Pushed a change to prevent bots from going for weapons they already have in inventory. They still seem to favor item gathering > fighting when there's the option but they are behaving much better.

**Comment by MrG-DRGN** [comment]
Reworked the way they seek health, as well.
